# МОДИФИЦИРОВАНО

# Setup
title:               Reducing Suffering
url:                 reducingsuffering.github.io
baseurl:             ''
permalink:           /:title:output_ext

# About/contact
email:               latif.rosh@gmail.com

# Custom vars
# google_analytics

collections:
  articles:
    output: true
    permalink: /:title:output_ext
  lists:
    output: false