# МОДИФИЦИРОВАНО

# Setup
title:               Reducing Suffering
url:                 reducingsuffering.github.io
baseurl:             ''
permalink:           /:title:output_ext

# Social networks
vk:                  https://vk.com/reducing_suffering
telegram:            https://t.me/reducing_suffering

# Admin contacts
admin:
  email: latif.rosh@gmail.com
  vk: https://vk.com/latif_rosh
  telegram: https://t.me/KKirdan
  patreon: https://www.patreon.com/user?u=120067868
  boosty: https://boosty.to/k_kirdan

# Custom vars
collections:
  articles:
    output: true
    permalink: /:title:output_ext
  lists:
    output: false
    
google_analytics: G-CZTR6P99H5
